---
language: ruby
cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.3

before_install:
  - gem update bundler

install:
  - bundle install --path vendor/bundle

branches:
  only:
  - master

script: bundle exec rake
